server:
  port: 81
spring:
  application:
    name: cloud-consumer-order81

eureka:
  client:
    # 表示是否将自己注册到EurekaServer默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单点无所谓。集群必须设置为true  才能配置ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
