server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848  # 配置nacos地址
        server-addr: 192.168.194.128:5555  # 配置nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'
