server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 当前数据库操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # mysql驱动包
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  # 连接zookeeper
  cloud:
    zookeeper:
      connect-string: 192.168.194.128:2181



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lea.sprongcloud.entities   # 所有Entity别名类所在包

